### ISSUE TITLE
after yarn starts

### ISSUE THREAD

**Issue by mahsa-frj** [gluster/glusterfs-hadoop#130]
Hi, i start yarn in my servers, and when i use jps command, the output shows me resourcemanager and nodemanager is running, now i have one question, how to test hadoop works true with glusterfs?
please help me.
thanks for your reply.

**Comment by jayunit100** [comment]
simple. just do `hadoop fs -ls /` and you should see all the directories in gluster's root.

**Comment by mahsa-frj** [comment]
thanks for your reply, @jayunit100 when i use above command ( hadoop fs -ls / ) i get this output:

``````
15/06/10 11:31:11 INFO glusterfs.GlusterVolume: Initializing gluster volume..
15/06/10 11:31:11 INFO glusterfs.GlusterFileSystem: Configuring GlusterFS
15/06/10 11:31:11 INFO glusterfs.GlusterFileSystem: Initializing GlusterFS,  CRC disabled.
15/06/10 11:31:11 INFO glusterfs.GlusterFileSystem: GIT INFO={git.commit.id.abbrev=f0fee73, git.commit.user.email=bchilds@redhat.com, git.commit.message.full=Merge pull request #122 from childsb/getfattrparse

Refactor and cleanup the BlockLocation parsing code, git.commit.id=f0fee73c336ac19461d5b5bb91a77e05cff73361, git.commit.message.short=Merge pull request #122 from childsb/getfattrparse, git.commit.user.name=bradley childs, git.build.user.name=Unknown, git.commit.id.describe=GA-12-gf0fee73, git.build.user.email=Unknown, git.branch=master, git.commit.time=31.03.2015 @ 00:36:46 IRDT, git.build.time=09.06.2015 @ 12:00:02 IRDT}
15/06/10 11:31:11 INFO glusterfs.GlusterFileSystem: GIT_TAG=GA
15/06/10 11:31:11 INFO glusterfs.GlusterFileSystem: Configuring GlusterFS
15/06/10 11:31:11 INFO glusterfs.GlusterVolume: Initializing gluster volume..
15/06/10 11:31:11 INFO glusterfs.GlusterVolume: Gluster volume: hadoop at : /mnt/hadoop
15/06/10 11:31:11 INFO glusterfs.GlusterVolume: Working directory is : /
15/06/10 11:31:11 INFO glusterfs.GlusterVolume: Write buffer size : 131072
15/06/10 11:31:11 INFO glusterfs.GlusterVolume: Default block size : 67108864
15/06/10 11:31:11 INFO glusterfs.GlusterVolume: Directory list order : fs ordering
15/06/10 11:31:11 INFO glusterfs.GlusterVolume: File timestamp lease significant digits removed : 0
-ls: Fatal internal error
 ``` java.lang.RuntimeException: Error undefined volume:hadoop1 in path: glusterfs://hadoop1/```
at org.apache.hadoop.fs.glusterfs.GlusterVolume.pathToFile(GlusterVolume.java:242)
at org.apache.hadoop.fs.glusterfs.GlusterVolume.getFileStatus(GlusterVolume.java:376)
at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:421)
at org.apache.hadoop.fs.Globber.getFileStatus(Globber.java:57)
at org.apache.hadoop.fs.Globber.glob(Globber.java:265)
at org.apache.hadoop.fs.FileSystem.globStatus(FileSystem.java:1655)
at org.apache.hadoop.fs.shell.PathData.expandAsGlob(PathData.java:326)
at org.apache.hadoop.fs.shell.Command.expandArgument(Command.java:235)
at org.apache.hadoop.fs.shell.Command.expandArguments(Command.java:218)
at org.apache.hadoop.fs.shell.Command.processRawArguments(Command.java:201)
at org.apache.hadoop.fs.shell.Command.run(Command.java:165)
at org.apache.hadoop.fs.FsShell.run(FsShell.java:287)
``````

it is so important for me to do that, please help me to understand where is my configuration is not correct, i think my core-site.xml's configuration is correct.

**Comment by mahsa-frj** [comment]
thanks, my problem solved.

**Comment by mahsa-frj** [comment]
sorry, what is the best tool for testing hadoop's performance?

**Comment by cb200664** [comment]
how to solve this problem,tanks

**Comment by jayunit100** [comment]
hi @mahsa-frj .  

0) There are terasort, teragen, and so on.   Those are available as part of your hadoop distribution in a jar file, and  are also curated in apache hadoop upstream.   They are very easy to run and are the most well known benchmarks for raw hadoop i/o and single job perf testing.

1) If you want a "full" testing solution for your hadoop cluster, you can use ASF BigTop's smoke test libraries, which run these tests for you, alongside other important tests (hadoop client tests, pig tests, hive tests, flume, and so on) (scale is configurable).  

2) Additionally the bigtop distribution has a realistic realistic test of the entire hadoop ecosystem (mapreduce->pig->mahout), you can try - its called  BigPetStore-Mapreduce application which isalso curated in BigTop : https://github.com/apache/bigtop/tree/master/bigtop-bigpetstore/bigpetstore-mapreduce.

**Comment by cb200664** [comment]
15/08/31 06:34:42 INFO mapreduce.Job: The url to track the job: http://cn0:8088/proxy/application_1441002854313_0001/
15/08/31 06:34:42 INFO mapreduce.Job: Running job: job_1441002854313_0001
15/08/31 06:34:52 INFO mapreduce.Job: Job job_1441002854313_0001 running in uber mode : false
15/08/31 06:34:52 INFO mapreduce.Job:  map 0% reduce 0%
15/08/31 06:34:52 INFO mapreduce.Job: Job job_1441002854313_0001 failed with state FAILED due to: Application application_1441002854313_0001 failed 2 times due to AM Container for appattempt_1441002854313_0001_000002 exited with  exitCode: -1000
For more detailed output, check application tracking page:http://cn0:8088/proxy/application_1441002854313_0001/Then, click on links to logs of each attempt.
Diagnostics: File glusterfs:/user/hadoop/.staging/job_1441002854313_0001/job.splitmetainfo does not exist.
java.io.FileNotFoundException: File glusterfs:/user/hadoop/.staging/job_1441002854313_0001/job.splitmetainfo does not exist.
        at org.apache.hadoop.fs.glusterfs.GlusterVolume.getFileStatus(GlusterVolume.java:368)
        at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:409)
        at org.apache.hadoop.yarn.util.FSDownload.copy(FSDownload.java:251)
        at org.apache.hadoop.yarn.util.FSDownload.access$000(FSDownload.java:61)
        at org.apache.hadoop.yarn.util.FSDownload$2.run(FSDownload.java:359)
        at org.apache.hadoop.yarn.util.FSDownload$2.run(FSDownload.java:357)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
        at org.apache.hadoop.yarn.util.FSDownload.call(FSDownload.java:356)
        at org.apache.hadoop.yarn.util.FSDownload.call(FSDownload.java:60)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Failing this attempt. Failing the application.
15/08/31 06:34:52 INFO mapreduce.Job: Counters: 0




why this happen? thanks.

**Comment by septianw** [comment]
Is this issue solved?
